version: 1.0.{build}
image: Visual Studio 2017
install:
- ps: >-
    $env:appveyor_nuget_push = 'false'

    if(-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
      if($env:appveyor_repo_tag -eq 'True') {
        if($env:appveyor_repo_tag_name -match '^[0-9]+\.[0-9]+') {
           $env:appveyor_nuget_push = 'true'
        }
      }
    }
build_script:
- cmd: nuget pack
test: off
artifacts:
- path: '*.nupkg'
  name: NuGet package
deploy:
- provider: NuGet
  api_key:
    secure: 7cthHh+wYWZjhqxaxR6QObRaRnstvFkQOY7MkxIsC5kpQEBlKZXuinf0IybbYxJt
  on:
    appveyor_nuget_push: true  